name: Build Application

on:
  # 手动触发工作流
  workflow_dispatch:
  # 如果你也想在发布时自动构建，取消下面的注释
  # release:
  #   types: [created]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller opencv-python
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --windowed --name "视频时长查看器" --clean --icon=vticon.ico video_duration.py
        
    - name: Create Release ZIP
      run: |
        cd dist
        7z a -tzip "../视频时长查看器.zip" "视频时长查看器"
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: 视频时长查看器
        path: 视频时长查看器.zip 